name: "Google Cloud SQL Proxy"
description: "Start Google CloudSQL Proxy"

branding:
  icon: "database"
  color: "red"

inputs:
  creds:
    description: "Contents of a Service Account JSON Key"
    required: true
  instance:
    description: "CloudSQL instance"
    required: true
  port:
    description: "Listen on port"
    required: false
    default: 5432
  proxy_version:
    description: "CloudSQL Proxy Version"
    required: false
    default: 1.18.0

runs:
  using: "composite"
  steps:
    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: |
        # write google application credentials to a temporary file to be used inside the container
        mkdir -p /tmp/gce-cloudsql-proxy
        echo '${{ inputs.creds }}' > /tmp/gce-cloudsql-proxy/key.json

        # start container
        docker run -d --net host --name gce-cloudsql-proxy --restart on-failure \
        -v /tmp/gce-cloudsql-proxy:/tmp/gce-cloudsql-proxy \
        gcr.io/cloudsql-docker/gce-proxy:${{ inputs.proxy_version }} \
        /cloud_sql_proxy \
          -credential_file /tmp/gce-cloudsql-proxy/key.json \
          -dir /tmp \
          -instances=${{ inputs.instance }}=tcp:127.0.0.1:${{ inputs.port }}

        # wait until connections are accepted
        sleep 3
        isready=0
        for i in {1..10}; do
          echo "Wait for connections to be ready ... $i/10"
          (${{ github.action_path }}/wait-for-it.sh --quiet --timeout=3 --host=127.0.0.1 --port=${{ inputs.port }} || exit $?) && true # escape bash's pipefail
          isready=$?
          if [[ $isready -eq 0 ]]; then
            break
          fi
          sleep 2
        done

        # print container logs
        docker logs gce-cloudsql-proxy

        # exit with error code if we couldn't connect
        if [[ $isready -ne 0 ]]; then
          exit $isready 
        fi
